/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    BaseBoard: typeof import('./../components/dropBoard/components/baseBoard.vue')['default']
    CopperModal: typeof import('./../components/Cropper/src/CopperModal.vue')['default']
    Cropper: typeof import('./../components/Cropper/src/Cropper.vue')['default']
    CropperAvatar: typeof import('./../components/Cropper/src/CropperAvatar.vue')['default']
    FontInfo: typeof import('./../components/FontInfo/src/FontInfo.vue')['default']
    Header: typeof import('./../components/header/index.vue')['default']
    HomeBoard: typeof import('./../components/dropBoard/homeBoard.vue')['default']
    InputPassword: typeof import('./../components/InputPassword/src/InputPassword.vue')['default']
    Message: typeof import('./../components/Message/src/Message.vue')['default']
    ProductBoard: typeof import('./../components/dropBoard/components/productBoard.vue')['default']
    ProductBoardItem: typeof import('./../components/dropBoard/components/productBoardItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInfo: typeof import('./../components/SearchInfo/src/SearchInfo.vue')['default']
    SubBoard: typeof import('./../components/dropBoard/subBoard.vue')['default']
    TileWaterfallBoard: typeof import('./../components/dropBoard/components/tileWaterfallBoard.vue')['default']
    UserInfo: typeof import('./../components/UserInfo/src/UserInfo.vue')['default']
    Verify: typeof import('./../components/Verifition/src/Verify.vue')['default']
    VerifyPoints: typeof import('./../components/Verifition/src/Verify/VerifyPoints.vue')['default']
    VerifySlide: typeof import('./../components/Verifition/src/Verify/VerifySlide.vue')['default']
    WaterfallBoard: typeof import('./../components/dropBoard/components/waterfallBoard.vue')['default']
    XButton: typeof import('./../components/XButton/src/XButton.vue')['default']
    XTextButton: typeof import('./../components/XButton/src/XTextButton.vue')['default']
  }
}
