/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

declare module 'vue' {
  export interface GlobalComponents {
    Verify: (typeof import('./../components/Verifition/src/Verify.vue'))['default']
    VerifyPoints: (typeof import('./../components/Verifition/src/Verify/VerifyPoints.vue'))['default']
    VerifySlide: (typeof import('./../components/Verifition/src/Verify/VerifySlide.vue'))['default']
  }
}
